### ISSUE TITLE
For loop causes cascade to hang

### ISSUE THREAD

**Issue by ynaffitgnay** [eschkufz/cascade#10]
## Overview
**Bug report.** Module with similar structure to [this example ](https://github.com/ynaffitgnay/CascadeBenches/blob/master/bugreports/for_loop_cascade_hang.v) hangs after one clock cycle. Removing the for loop defined on lines 130-132 causes the display statement to print every cycle, as expected. May be related to [this issue](https://github.com/eschkufz/cascade/issues/9#issue-598575966).

**Comment by eschkufz** [comment]
This is a tough one. And I'm leaning towards calling it correct behavior according to the spec.

We have a for loop inside of an always @* block. Since the iterator variable is dereferenced (both by the loop condition and the assignment) it's added to the sensitivity list of the always block. But because the for loop writes the value of the iterator variable as well, it's constantly re-triggering the always block. And even though the iterator is declared as an integer (which is a reg), it's only ever used in this context, so we're forced to demote it to a wire. As a result, I think what that amounts to is a zero time loop.

Intuitively, this feels wrong to me, but I can't find anything in the spec (like a clause about how for loop iterators are exempt from triggering procedural control events) to say otherwise.

There are two fixes I can see for the code in question:
1. (less obvious) Replace the always @* with an explicit list that doesn't contain the iterator variable.
2. (better) replace the for loop with an assignment to zero ```outbuf_pop = 0```
