### ISSUE TITLE
Wire driven by another module causes Cascade to hang

### ISSUE THREAD

**Issue by ynaffitgnay** [eschkufz/cascade#9]
## Overview

**Bug report.** 
When instantiating a module with the same structure as [this sample](https://github.com/ynaffitgnay/CascadeBenches/blob/master/bugreports/cascade_hang.v), Cascade never starts up verilator. If `!macroWrQ_empty` is replaced with the variable `not_macroWrQ_empty`, the code seems to run properly. Removing the for loop defined from lines 83-85 prevents Cascade from hanging.

**Comment by eschkufz** [comment]
So now this is *really* interesting. This is related to issue 10 in that the for loop is the root cause of the hanging. Here's how I'm thinking about this one.

1. A zero-time loop is undefined according to the spec, so hanging is a valid (if annoying) interpretation of such a loop. 
2. Cascade's software backend is a lazy simulator. This means it won't calculate the value of part of your program unless it has to.
3. So we can actually get around this loop if there's nothing in your program that causes Cascade's software backend to think it ever has to evaluate it (side bar: it *should* be able to look at your code and warn you that this is the case, but that's for another feature request).
4. And here's what's really cool: the loop is only a zero-time simulator hang once you're in it. It can't trigger itself. If the only thing in the always @* block is the loop, then only i goes into the sensitivity list, and if the loop is the only place i is written, it'll never fire.

So what's making a difference here is the other variable that makes it into the sensitivity list (macroRqEmpty or not_macroRqEmpty). Technically the code is the same either way, but it triggers a slightly different code path in cascade's simulator depending on which you use. One triggers a single evaluation of the block (which leads to a kajillion more) and the other doesn't.

So... technically correct. Which is the worst kind of correct. I argue the code is undefined which means Cascade could blow up your computer and I'd still say it was correct.

**Comment by ynaffitgnay** [comment]
I’m furious about this, but I understand. I will work through this with my therapist. Thank you.

---

Tiffany Yang
M.S. Student
Computer Science
The University of Texas at Austin
713-376-1755
